### ISSUE TITLE
A missing step in README.md, I believe

### ISSUE THREAD

**Issue by LordJuss** [michaelsnook/flaskr-heroku#2]
I've worked through the instructions in README.md, and I'm having the same problem I had
before I ran across your project on git-hub.  I believe the problem is that the database isn't being
created when the app tries to run on heroku.  Here's my heroku log:

2015-02-27T22:24:58.387273+00:00 heroku[api]: Deploy 9a820e2 by rware@alum.mit.edu
2015-02-27T22:24:58.387273+00:00 heroku[api]: Release v4 created by rware@alum.mit.edu
2015-02-27T22:24:58.525090+00:00 heroku[web.1]: State changed from crashed to starting
2015-02-27T22:25:04.381554+00:00 heroku[web.1]: Starting process with command `gunicorn flaskr:app -p 5000`
2015-02-27T22:25:07.726726+00:00 app[web.1]: [2015-02-27 22:25:07 +0000] [3] [INFO] Starting gunicorn 19.2.1
2015-02-27T22:25:07.787439+00:00 app[web.1]: [2015-02-27 22:25:07 +0000] [10] [INFO] Booting worker with pid: 10
2015-02-27T22:25:07.730411+00:00 app[web.1]: [2015-02-27 22:25:07 +0000] [3] [INFO] Listening at: http://0.0.0.0:25639 (3)
2015-02-27T22:25:07.730513+00:00 app[web.1]: [2015-02-27 22:25:07 +0000] [3] [INFO] Using worker: sync
2015-02-27T22:25:07.747846+00:00 app[web.1]: [2015-02-27 22:25:07 +0000] [9] [INFO] Booting worker with pid: 9
2015-02-27T22:25:07.918571+00:00 heroku[web.1]: State changed from starting to up
2015-02-27T22:25:42.328168+00:00 heroku[api]: Scale to web=1 by rware@alum.mit.edu
2015-02-27T22:26:39.933834+00:00 heroku[router]: at=info method=GET path="/" host=gentle-beyond-2639.herokuapp.com request_id=253cf904-c389-49c3-a4cd-f932399f57a8 fwd="75.173.230.213" dyno=web.1 connect=2ms service=9ms status=500 bytes=244
2015-02-27T22:26:39.944166+00:00 app[web.1]: [2015-02-27 22:26:39 +0000] [9] [ERROR] Error handling request
2015-02-27T22:26:39.944171+00:00 app[web.1]: Traceback (most recent call last):
2015-02-27T22:26:39.944173+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 129, in handle
2015-02-27T22:26:39.944174+00:00 app[web.1]:     self.handle_request(listener, req, client, addr)
2015-02-27T22:26:39.944178+00:00 app[web.1]:     respiter = self.wsgi(environ, resp.start_response)
2015-02-27T22:26:39.944176+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 170, in handle_request
2015-02-27T22:26:39.944179+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1836, in **call**
2015-02-27T22:26:39.944181+00:00 app[web.1]:     return self.wsgi_app(environ, start_response)
2015-02-27T22:26:39.944183+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
2015-02-27T22:26:39.944184+00:00 app[web.1]:     response = self.make_response(self.handle_exception(e))
2015-02-27T22:26:39.944185+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
2015-02-27T22:26:39.944187+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2015-02-27T22:26:39.944189+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
2015-02-27T22:26:39.944190+00:00 app[web.1]:     response = self.full_dispatch_request()
2015-02-27T22:26:39.944191+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
2015-02-27T22:26:39.944193+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2015-02-27T22:26:39.944194+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
2015-02-27T22:26:39.944196+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2015-02-27T22:26:39.944199+00:00 app[web.1]:     rv = self.dispatch_request()
2015-02-27T22:26:39.944200+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
2015-02-27T22:26:39.944201+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2015-02-27T22:26:39.944203+00:00 app[web.1]:   File "/app/flaskr.py", line 41, in show_entries
2015-02-27T22:26:39.944197+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
2015-02-27T22:26:39.944204+00:00 app[web.1]:     cur = g.db.execute('select title, text from entries order by id desc')
2015-02-27T22:26:39.944206+00:00 app[web.1]: OperationalError: no such table: entries
2015-02-27T22:26:40.347156+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=gentle-beyond-2639.herokuapp.com request_id=a4d5e5d1-31d2-4cb3-aaae-4ea140f9f20f fwd="75.173.230.213" dyno=web.1 connect=2ms service=24ms status=404 bytes=386
2015-02-27T22:26:44.525802+00:00 heroku[router]: at=info method=GET path="/" host=gentle-beyond-2639.herokuapp.com request_id=6228e00c-00f1-4912-859f-fc497f953008 fwd="75.173.230.213" dyno=web.1 connect=2ms service=16ms status=500 bytes=244
2015-02-27T22:26:44.538782+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 170, in handle_request
2015-02-27T22:26:44.538778+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 129, in handle
2015-02-27T22:26:44.538780+00:00 app[web.1]:     self.handle_request(listener, req, client, addr)
2015-02-27T22:26:44.538783+00:00 app[web.1]:     respiter = self.wsgi(environ, resp.start_response)
2015-02-27T22:26:44.538790+00:00 app[web.1]:     response = self.make_response(self.handle_exception(e))
2015-02-27T22:26:44.538770+00:00 app[web.1]: [2015-02-27 22:26:44 +0000] [10] [ERROR] Error handling request
2015-02-27T22:26:44.538776+00:00 app[web.1]: Traceback (most recent call last):
2015-02-27T22:26:44.538791+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
2015-02-27T22:26:44.538785+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1836, in **call**
2015-02-27T22:26:44.538787+00:00 app[web.1]:     return self.wsgi_app(environ, start_response)
2015-02-27T22:26:44.538794+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
2015-02-27T22:26:44.538796+00:00 app[web.1]:     response = self.full_dispatch_request()
2015-02-27T22:26:44.538793+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2015-02-27T22:26:44.538803+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
2015-02-27T22:26:44.538797+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
2015-02-27T22:26:44.538788+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
2015-02-27T22:26:44.538804+00:00 app[web.1]:     rv = self.dispatch_request()
2015-02-27T22:26:44.538798+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2015-02-27T22:26:44.538800+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
2015-02-27T22:26:44.538810+00:00 app[web.1]:     cur = g.db.execute('select title, text from entries order by id desc')
2015-02-27T22:26:44.538801+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2015-02-27T22:26:44.538807+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2015-02-27T22:26:44.538805+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
2015-02-27T22:26:44.538808+00:00 app[web.1]:   File "/app/flaskr.py", line 41, in show_entries
2015-02-27T22:26:44.538811+00:00 app[web.1]: OperationalError: no such table: entries

**Comment by mhsnook** [comment]
Interesting! Thanks for spotting this. Do you know how to fix it? I can't immediately tell from these error messages what's going on.
